kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: multinode-cluster
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 30001
      hostPort: 8080
  - role: worker
  - role: worker
  - role: worker
