apiVersion: v1
kind: Service
metadata:
  name: library-service
spec:
  type: NodePort
  selector:
    app: library-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-pod
  template:
    metadata:
      labels:
        app: library-pod
    spec:
      containers:
      - name: library-container
        image: spikatrix/library-go
        ports: 
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: mongodb-uri